### ISSUE TITLE
Print error message instead of index-out-of-range panic (was: Should verify input-buffer)

### ISSUE THREAD

**Issue by ineiti** [dedis/protobuf#18]
When the input-buffer is larger than the data, it will try to decode anyway, but fail on printing an error, as the index is out of range in

decode.go:107

```
if err != nil {
	return fmt.Errorf("FieldName %s: %v", fields[fieldi].Name, err)
}
```

**Comment by Liamsi** [comment]
I would change this to `if err != nil && len(fields) <= fieldi` and add a case `if len(fields) > fieldi` to print the  other error.

**Comment by ineiti** [comment]
Can you do this, please? Sounds like a good solution.

**Comment by Liamsi** [comment]
> Can you do this, please? Sounds like a good solution.

Yes of course. I looked a little through the code:
The 2nd if statement: `if len(fields) >= fieldi` would always throw an error at the end because the way fieldi is computed here: https://github.com/dedis/protobuf/blob/master/decode.go#L88-L90
Wouldn't it make more sense to move 
https://github.com/dedis/protobuf/blob/master/decode.go#L104-L108
into the `if` statement above it: https://github.com/dedis/protobuf/blob/master/decode.go#L92-L102
This would have the same effect. If the buffer is too long and contains some junk, calling `value(...)` would either return an error or panic.
