### ISSUE TITLE
Required/optional default value differences.

### ISSUE THREAD

**Issue by jackowitz** [dedis/protobuf#4]
I noticed that `Encode()` assumes that all `[]byte` are required fields by default but assumes that pointers are optional by default. Is this difference intentional? Is so, we should probably make this fact clearer in the examples as it (for me at least) was unexpected.

**Comment by alecthomas** [comment]
It is intentional, yes, and documented: "An 'optional' protobuf field is expressed as a pointer field in Go.". That said, it is just one sentence and can be easily overlooked, so perhaps it should be more prominent. It's also shown in the `.proto` generation example, but that output is a little disassociated from the original struct definitions so perhaps it is not clear. If you can restructure the README to be clearer, it would be good.

**Comment by jackowitzd2** [comment]
Thanks for the info. I probably should have given more context - the fact that pointers are optional is clear from the docs, it was the byte slices that I was surprised about. Since, like pointers, slices have a ```nil``` zero value, my expectation was that they would receive the same default treatment. Looking further, I'm even more confused, as it seems that it is only slices of the ```[]byte``` variety that are required by default. Consider the following:
```go
package main

import (
    "fmt"
    "github.com/dedis/protobuf"
)

type Pass struct {
    Other []int
}

type Fail struct {
    Bytes []byte
}

func main() {
    if _, err := protobuf.Encode(new(Pass)); err != nil {
        fmt.Println(err.Error())
    }
    if _, err := protobuf.Encode(new(Fail)); err != nil {
        fmt.Println(err.Error())
    }   
}
```

This outputs: ```passed nil []byte to required field (field Bytes)```; the ```nil``` ```[]int``` encodes fine as a zero-length slice, which is what I was expecting for the ```[]byte``` as well. So my question really should have been "Is there a reason we're special casing ```[]byte``` and making it required by default while other types of slices are optional?".

**Comment by jackowitzd2** [comment]
Just reviving this issue to see if anyone has additional feedback...

**Comment by bford** [comment]
Thanks for the reminder.  Indeed, if it's specific to []byte, it sounds like just a bug or oversight rather than any kind of intent.  It should probably be consistent one way or the other - for consistency with common Go practice this might suggest making the encoding of any nil slice (including []byte) equivalent to encoding a zero-length slice of the same type.
