### ISSUE TITLE
(Un)MarshalBinary only used on Interface types.

### ISSUE THREAD

**Issue by jackowitz** [dedis/protobuf#5]
In the current implementation, `(Un)MarshalBinary` is only used in the case when the field is of an interface type. Is there a strong reason behind this design rather than delegating to any type (interface or not) that offers to handle (un)marshaling itself?

**Comment by jackowitzd2** [comment]
Following up with a specific example: ```*PubPoly``` from the crypto library. In order to make use of its custom marshaling functionality, currently you have to play games with treating it as an ```interface{}``` and then asserting it back to the actual type. Not the end of the world, but also not the cleanest/clearest.

**Comment by bford** [comment]
Very good question - no, that issue really didn't come up or occur to me explicitly when I was first implementing the protobuf code.  It's more of an oversight than a design decision. :)

Does it work simply to move the BinaryMarshaler-invoking code from the reflect.Interface branch of the second switch statement in encoder.value(), up into the first type-switch in the same function?

The corresponding decode code will still need a bit of of special code to handle constructor-invocation in the case of a null-pointer-to-struct, but perhaps in that case we won't actually need a constructor to be in the Constructors since we should be able to construct an instance of the specific required struct via reflection?

**Comment by ineiti** [comment]
If you have two structures like the following, then calling `protobuf.Encode(B{})` will not call `MarshalBinary` of `A`.

Wanted:
- if a structure is a `BinaryMarshaler`, then `protobuf.Encode` should use this and encode the result as `bytes`
- if a structure is a `BinaryUnmarshaler`, then `protobuf.Decode` should use this to decode the fields

```
type A struct{
  Value int
}

func (a *A)MarshalBinary()([]byte, error){
  return []byte{a.Value}, nil
}

type B struct{
  AValue A
}
```
