### ISSUE TITLE
go.dedis.ch can go offline due to DNS outage

### ISSUE THREAD

**Issue by alecthomas** [dedis/protobuf#67]
And thus prevents use of this package.

-- 

We've chosen to use AWS Route 53 for DNS.

Here are the steps to go forward:
- [x] import dedis.ch into route 53
- [x] figure out interaction between the go.dedis.ch Amazon Cert and the Route 53 alias mechanism
- [x] decide what to do about the invalid MX record - removed it
- [x] import cothority.net into route 53
- [x] update NS records for cothority.net as a test
- [x] update NS records for dedis.ch
- [x] turn off bind and remove port 53 from the UFW config on dedis-ns[12].epfl.ch
- [x] organise transfer from the current registrars to Amazon: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-to-route-53.html#domain-transfer-to-route-53-confirm-tld

**Comment by jeffallen** [comment]
I can't reproduce this right now, I don't think it is happening anymore.

go.dedis.ch is a CNAME to d-8jq79za180.execute-api.eu-central-1.amazonaws.com, which is the API endpoint for a lambda that actually generates the redirects.

So go.dedis.ch depends on two things being up: the DNS servers for dedis.ch, and Amazon. This is already a big improvement from before, when we hosted the web server. However, it is true that our DNS servers can also be flaky.

I have raised the TTL on go.dedis.ch to 24 hours, so that if a DNS resolver between you and us has a copy of our record, then short DNS outages will not be noticeable.

I am also leaving this issue open as a reminder that we should consider moving DNS to a more reliable provider than we currently use.

**Comment by jeffallen** [comment]
The dedis.ch domain also needs to be moved to a more reliable registrar (or at least one that we can communicate directly with, so that we get expiration notices). Because go.dedis.ch already depends on AWS, I suppose the best choice would be AWS Route 53.

**Comment by Gilthoniel** [comment]
AWS Route 53 cost 0.50$ per hosted zone (so 1 in our case) which is nice.

**Comment by jeffallen** [comment]
Done.
