### ISSUE TITLE
protobuf not working for suite.Point().Null() 

### ISSUE THREAD

**Issue by iuliatamas** [DeDiS/protobuf#7]
Say I have a structure with 

```go
type a struct {
      b abstract.Point
}
```

and I set b to  suite.Point().Null() ( where suite is already good and intialized)
If I Marshal a via protobuf and I send it via the network, when I Get it I error with "failed to unmarshal binary"

Any other Point value works. If b==nil it also works. At the moment, as a workaround, I perform a check and if b is Point.Null() I just make it equal to nil and send it like that.

Is this what is expected?

**Comment by jackowitzd2** [comment]
My first thought is that this probably isn't in protobuf, but crypto, since it's only happening with a specific Point value and Point handles unmarshaling itself. Can you call (Un)MarshalBinary directly on the Point and get the expected results? If it fails then too, then maybe re-open this issue in crypto?

**Comment by iuliatamas** [comment]
Ok. I am re-opening the issue in crypto with a small test to show the behavior.
